return {
	"Civitasv/cmake-tools.nvim",
	ft = { "cmake", "c", "cpp" },
	cmd = {
		"CMakeGenerate",
		"CMakeBuild",
		"CMakeRun",
		"CMakeDebug",
		"CMakeOpen",
		"CMakeClose",
		"CMakeInstall",
		"CMakeClean",
		"CMakeStop",
		"CMakeReset",
		"CMakeQuickBuild",
		"CMakeQuickRun",
		"CMakeQuickDebug",
		"CMakeSelectBuildTarget",
		"CMakeSelectLaunchTarget",
		"CMakeSelectKit",
		"CMakeSelectConfigurePreset",
		"CMakeSelectBuildPreset",
		"CMakeSelectBuildType",
	},
	dependencies = { "nvim-lua/plenary.nvim" },
	keys = {
		{ "<leader>cg", "<cmd>CMakeGenerate<cr>", desc = "CMake generate" },
		{ "<leader>cb", "<cmd>CMakeBuild<cr>", desc = "CMake build" },
		{ "<leader>cR", "<cmd>CMakeRun<cr>", desc = "CMake run" },
		{ "<leader>cd", "<cmd>CMakeDebug<cr>", desc = "CMake debug" },
		{ "<leader>ct", "<cmd>CMakeSelectBuildTarget<cr>", desc = "CMake select target" },
	},
	opts = {
		cmake_command = "cmake",
		cmake_build_directory = "build",
		cmake_build_directory_prefix = "",
		cmake_soft_link_compile_commands = true,
		cmake_compile_commands_from_lsp = false,
		cmake_kits_path = nil,
		cmake_variants_message = {
			short = { show = true },
			long = { show = true, max_length = 40 },
		},
		cmake_dap_configuration = {
			name = "cpp",
			type = "codelldb",
			request = "launch",
			stopOnEntry = false,
			runInTerminal = true,
			console = "integratedTerminal",
		},
		cmake_executor = {
			name = "quickfix",
		},
		cmake_runner = {
			name = "terminal",
		},
	},
}
